# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.aldgmrfld0 <- function(pars, yc, C, tau) {
    .Call(`_evgmrf_aldgmrfld0`, pars, yc, C, tau)
}

.aldgmrfld1 <- function(pars, yc, C, tau) {
    .Call(`_evgmrf_aldgmrfld1`, pars, yc, C, tau)
}

.aldgmrfld2 <- function(pars, yc, C, tau) {
    .Call(`_evgmrf_aldgmrfld2`, pars, yc, C, tau)
}

.ald0 <- function(pars, yv, C, tau) {
    .Call(`_evgmrf_ald0`, pars, yv, C, tau)
}

.ald1 <- function(pars, yv, C, tau) {
    .Call(`_evgmrf_ald1`, pars, yv, C, tau)
}

.ald2 <- function(pars, yv, C, tau) {
    .Call(`_evgmrf_ald2`, pars, yv, C, tau)
}

.eig1 <- function(A) {
    .Call(`_evgmrf_eig1`, A)
}

.tgevgmrfld0 <- function(pars, yc, wc) {
    .Call(`_evgmrf_tgevgmrfld0`, pars, yc, wc)
}

.tgevgmrfld12 <- function(pars, yc, wc) {
    .Call(`_evgmrf_tgevgmrfld12`, pars, yc, wc)
}

.tgevgmrfldJ <- function(pars, yc, wc) {
    .Call(`_evgmrf_tgevgmrfldJ`, pars, yc, wc)
}

.tgevgmrfld0_omp <- function(pars, yc, wc, threads = 0L) {
    .Call(`_evgmrf_tgevgmrfld0_omp`, pars, yc, wc, threads)
}

.tgevgmrfld12_omp <- function(pars, yc, wc, threads = 0L) {
    .Call(`_evgmrf_tgevgmrfld12_omp`, pars, yc, wc, threads)
}

.tgev0 <- function(pars, yv, delta) {
    .Call(`_evgmrf_tgev0`, pars, yv, delta)
}

.tgev1 <- function(pars, yv, delta) {
    .Call(`_evgmrf_tgev1`, pars, yv, delta)
}

.tgev2 <- function(pars, yv, delta) {
    .Call(`_evgmrf_tgev2`, pars, yv, delta)
}

.tgpdgmrfld0 <- function(pars, yc) {
    .Call(`_evgmrf_tgpdgmrfld0`, pars, yc)
}

.tgpdgmrfld12 <- function(pars, yc) {
    .Call(`_evgmrf_tgpdgmrfld12`, pars, yc)
}

.tgpd0 <- function(pars, yv) {
    .Call(`_evgmrf_tgpd0`, pars, yv)
}

.tgpd1 <- function(pars, yv) {
    .Call(`_evgmrf_tgpd1`, pars, yv)
}

.tgpd2 <- function(pars, yv) {
    .Call(`_evgmrf_tgpd2`, pars, yv)
}

.tppugmrfld0 <- function(pars, uv, w) {
    .Call(`_evgmrf_tppugmrfld0`, pars, uv, w)
}

.tppugmrfld12 <- function(pars, uv, w) {
    .Call(`_evgmrf_tppugmrfld12`, pars, uv, w)
}

.tppzgmrfld0 <- function(pars, yc) {
    .Call(`_evgmrf_tppzgmrfld0`, pars, yc)
}

.tppzgmrfld12 <- function(pars, yc) {
    .Call(`_evgmrf_tppzgmrfld12`, pars, yc)
}

.tppu0 <- function(pars, u, w) {
    .Call(`_evgmrf_tppu0`, pars, u, w)
}

.tppu1 <- function(pars, u, w) {
    .Call(`_evgmrf_tppu1`, pars, u, w)
}

.tppu2 <- function(pars, u, w) {
    .Call(`_evgmrf_tppu2`, pars, u, w)
}

.tppz0 <- function(pars, zv) {
    .Call(`_evgmrf_tppz0`, pars, zv)
}

.tppz1 <- function(pars, zv) {
    .Call(`_evgmrf_tppz1`, pars, zv)
}

.tppz2 <- function(pars, zv) {
    .Call(`_evgmrf_tppz2`, pars, zv)
}

.tpp0 <- function(pars, zv, w, u, delta) {
    .Call(`_evgmrf_tpp0`, pars, zv, w, u, delta)
}

.tpp1 <- function(pars, zv, w, u, delta) {
    .Call(`_evgmrf_tpp1`, pars, zv, w, u, delta)
}

.tpp2 <- function(pars, zv, w, u, delta) {
    .Call(`_evgmrf_tpp2`, pars, zv, w, u, delta)
}

.tpprocgmrfld0 <- function(pars, yc, mult) {
    .Call(`_evgmrf_tpprocgmrfld0`, pars, yc, mult)
}

.tpprocgmrfld12 <- function(pars, yc, mult) {
    .Call(`_evgmrf_tpprocgmrfld12`, pars, yc, mult)
}

.rlargegmrfld0 <- function(pars, yc, wc) {
    .Call(`_evgmrf_rlargegmrfld0`, pars, yc, wc)
}

.rlargegmrfld12 <- function(pars, yc, wc) {
    .Call(`_evgmrf_rlargegmrfld12`, pars, yc, wc)
}

.rlarged0 <- function(pars, yv) {
    .Call(`_evgmrf_rlarged0`, pars, yv)
}

.rlarged1 <- function(pars, yv) {
    .Call(`_evgmrf_rlarged1`, pars, yv)
}

.rlarged2 <- function(pars, yv) {
    .Call(`_evgmrf_rlarged2`, pars, yv)
}

.rlargecgmrfld0 <- function(pars, yc, drop) {
    .Call(`_evgmrf_rlargecgmrfld0`, pars, yc, drop)
}

.rlargecgmrfld12 <- function(pars, yc, drop) {
    .Call(`_evgmrf_rlargecgmrfld12`, pars, yc, drop)
}

.cholAb <- function(A, b) {
    .Call(`_evgmrf_chol_logdet_solve`, A, b)
}

.ldchol <- function(A) {
    .Call(`_evgmrf_chol_logdet`, A)
}

.cholsolveAB <- function(A, B) {
    .Call(`_evgmrf_chol_solve_mat`, A, B)
}

